import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import {Theme} from "@radix-ui/themes";
import '@radix-ui/themes/styles.css';
import AppBar from "@/components/appBar";

const inter = Poppins({weight:['500','600','700','800'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-sage1 `}>
      <Theme>
        <AppBar/>
        {children}
      </Theme>
      </body>
    </html>
  );
}
